#!/bin/bash

set -e

echo
echo "### HOOK - build environment:"
echo "   SOURCE_BRANCH  : $SOURCE_BRANCH"
echo "   SOURCE_COMMIT  : $SOURCE_COMMIT"
echo "   COMMIT_MSG     : $COMMIT_MSG"
echo "   DOCKER_REPO    : $DOCKER_REPO"
echo "   DOCKERFILE_PATH: $DOCKERFILE_PATH"
echo "   DOCKER_TAG     : $DOCKER_TAG"
echo "   DOCKER_TAG     : $IMAGE_NAME"

# Build synthea distribution tar file
./build_synthea.sh

# Containerize synthea
docker build -t ${DOCKER_REPO}:readmission-demo .

# Run synthea to generate 5000 patients with seed 1577991349289 for the readmission demo
docker run --rm -v $PWD/output:/output --name synthea-docker ${DOCKER_REPO}:readmission-demo -p 5000 -s 1577991349289

# Compress generated patients into a tar to be added to an empty image
tar -czvf ./image-5000patients/patient-data.tar.gz ./output
rm -rf output

# Creating an empty image that will ADD patient-data.tar.gz to it
docker build -t ${DOCKER_REPO}:readmission-demo-5000 ./image-5000patients
